### ISSUE TITLE
大佬，打包失败

### ISSUE THREAD

**Issue by wclmgcd** [zhangguanzhang/Actions-OpenWrt#1]
打包时，内核地址时这个，
Cloning into '/opt/openwrt_packit'...
--2021-09-28 00:30:22--  https://raw.githubusercontent.com/breakings/OpenWrt/main/opt/kernel/5.14.8/boot-5.14.8-flippy-65+.tar.gz

可是原文件的5.14.8的内核名是boot-5.14.8-65 + .tar.gz ，所以下载失败，小白一个要修改哪里？

**Comment by zhangguanzhang** [comment]
> 打包时，内核地址时这个，
> Cloning into '/opt/openwrt_packit'...
> --2021-09-28 00:30:22-- https://raw.githubusercontent.com/breakings/OpenWrt/main/opt/kernel/5.14.8/boot-5.14.8-flippy-65+.tar.gz
> 
> 可是原文件的5.14.8的内核名是boot-5.14.8-65 + .tar.gz ，所以下载失败，小白一个要修改哪里？

https://github.com/zhangguanzhang/Actions-OpenWrt/blob/main/build/N1/diy-after.sh
可以参照我这个脚本，注意下路径，打包用的f大的

**Comment by zhangguanzhang** [comment]
```
export kernel_URL=https://raw.githubusercontent.com/breakings/OpenWrt/main/opt/kernel
export kernel_VER=5.14.8
wget ${kernel_URL}/${kernel_VER}/boot-${KERNEL_VERSION}.tar.gz
```

**Comment by zhangguanzhang** [comment]
你看下我修改的这个加上去就行了 https://github.com/zhangguanzhang/Actions-OpenWrt/commit/747616853b8097ebc806522daab503a49b7895da

**Comment by wclmgcd** [comment]
还是不行，是不是我添加晚了？我是在进行到compile the firmware这一步改的diy-after.sh，是不是太迟了？
 还有一个问题，我编译的固件只有8k，编译不成功，我是直接frok你的代码，直接把86 和R2S的文件夹删除，然后把config.buildinfo改成自己的，按照 unifreq /openwrt_packit的推荐

Target System  ->  QEMU ARM Virtual Machine 
Subtarget ->  QEMU ARMv8 Virtual Machine (cortex-a53)
Target Profile  ->  Default
Target Images  ->   tar.gz
*** 必选软件包(基础依赖包，仅保证打出的包可以写入EMMC,可以在EMMC上在线升级，不包含具体的应用)： 
Languages -> Perl               
             ->  perl-http-date
             ->  perlbase-getopt
             ->  perlbase-time
             ->  perlbase-unicode                              
             ->  perlbase-utf8        
Utilities -> Disc -> blkid、fdisk、lsblk、parted            
          -> Filesystem -> attr、btrfs-progs(Build with zstd support)、chattr、dosfstools、
                           e2fsprogs、f2fs-tools、f2fsck、lsattr、mkf2fs、xfs-fsck、xfs-mkfs
          -> Compression -> bsdtar 或 p7zip(非官方源)、pigz
          -> Shells  ->  bash         
          -> gawk、getopt、losetup、tar、uuidgen

 * (可选)Wifi基础包：
 *     打出的包可支持博通SDIO无线模块,Firmware不用选，
 *     因为打包源码中已经包含了来自Armbian的firmware，
 *     会自动覆盖openwrt rootfs中已有的firmware
 Kernel modules  ->   Wireless Drivers -> kmod-brcmfmac(SDIO) 
                                       -> kmod-brcmutil
                                       -> kmod-cfg80211
                                       -> kmod-mac80211
 Network  ->  WirelessAPD -> hostpad-common
                          -> wpa-cli
                          -> wpad-basic
          ->  iw，

自己加入
luci-app-adblock-plus，koolproxy，passwall，openclash，网易音乐解锁，zerotier，可是运行build-openwrt-matrix.yml或build-openwrt-single.yml，编译的固件只有8k，我看有一次失败也是这样，是什么问题？

**Comment by zhangguanzhang** [comment]
> 还是不行，是不是我添加晚了？我是在进行到compile the firmware这一步改的diy-after.sh，是不是太迟了？
> 还有一个问题，我编译的固件只有8k，编译不成功，我是直接frok你的代码，直接把86 和R2S的文件夹删除，然后把config.buildinfo改成自己的，按照 unifreq /openwrt_packit的推荐
> 
> Target System -> QEMU ARM Virtual Machine
> Subtarget -> QEMU ARMv8 Virtual Machine (cortex-a53)
> Target Profile -> Default
> Target Images -> tar.gz
> *** 必选软件包(基础依赖包，仅保证打出的包可以写入EMMC,可以在EMMC上在线升级，不包含具体的应用)：
> Languages -> Perl
> -> perl-http-date
> -> perlbase-getopt
> -> perlbase-time
> -> perlbase-unicode
> -> perlbase-utf8
> Utilities -> Disc -> blkid、fdisk、lsblk、parted
> -> Filesystem -> attr、btrfs-progs(Build with zstd support)、chattr、dosfstools、
> e2fsprogs、f2fs-tools、f2fsck、lsattr、mkf2fs、xfs-fsck、xfs-mkfs
> -> Compression -> bsdtar 或 p7zip(非官方源)、pigz
> -> Shells -> bash
> -> gawk、getopt、losetup、tar、uuidgen
> 
> * (可选)Wifi基础包：
> * ```
>   打出的包可支持博通SDIO无线模块,Firmware不用选，
>   ```
> * ```
>   因为打包源码中已经包含了来自Armbian的firmware，
>   ```
> * ```
>   会自动覆盖openwrt rootfs中已有的firmware
>   ```
> 
> Kernel modules -> Wireless Drivers -> kmod-brcmfmac(SDIO)
> -> kmod-brcmutil
> -> kmod-cfg80211
> -> kmod-mac80211
> Network -> WirelessAPD -> hostpad-common
> -> wpa-cli
> -> wpad-basic
> -> iw，
> 
> 自己加入
> luci-app-adblock-plus，koolproxy，passwall，openclash，网易音乐解锁，zerotier，可是运行build-openwrt-matrix.yml或build-openwrt-single.yml，编译的固件只有8k，我看有一次失败也是这样，是什么问题？

内核文件下载失败，打包阶段失败了，所以最后有问题，你可以先等我的action跑完，没问题了你再去你那run下action

**Comment by wclmgcd** [comment]
好

**Comment by zhangguanzhang** [comment]
明天早上起来看看我action，应该修复了

**Comment by zhangguanzhang** [comment]
https://github.com/zhangguanzhang/Actions-OpenWrt/blob/main/build/N1/diy-after.sh
你把我这个文件内容覆盖提交你仓库去就行了

**Comment by wclmgcd** [comment]
ok

**Comment by wclmgcd** [comment]
还有一个问题，我是要用+o的内核，直接修改
if grep -qw 'KERNEL_VERSION="5.14.8-flippy-65+"' /opt/openwrt_packit/make.env ;then
    export KERNEL_VERSION='5.14.8-65+'
    sed -ri 's#(^\s*KERNEL_VERSION=)"5.14.8-flippy-65\+"#\15.14.8-65+#' /opt/openwrt_packit/make.env
fi
这里成 5.4.149-65+o吗？

**Comment by zhangguanzhang** [comment]
我再改下处理下这个吧

**Comment by zhangguanzhang** [comment]
刚加了下input选项，可以输入内核版本，你可以复制过去试试

**Comment by zhangguanzhang** [comment]
我看现在能编译了

**Comment by wclmgcd** [comment]
我是不是填错了？build/${target} to build  我填N1,   N1 kernal 我填5.4.149,  没有打包内核

**Comment by zhangguanzhang** [comment]
5.4.149-65+

**Comment by wclmgcd** [comment]
感谢

**Comment by zhangguanzhang** [comment]
我昨天改了下，能自适应那个内核仓库的文件里版本号名字了。这个issue我就关闭了
