### ISSUE TITLE
SFT1200编译Initialization environment报错

### ISSUE THREAD

**Issue by Misaka-Aki** [zhangguanzhang/Actions-OpenWrt#2]
报错：
/home/runner/work/_temp/ccd34e11-7ef9-43b3-9c7a-74e23eaca492.sh: line 25: syntax error near unexpected token `newline'

地址：https://github.com/Misaka-Aki/Actions-OpenWrt/actions
原封不动运行了一次，改了git账户运行了一次，都报错
好像是sh脚本换行符的问题，之前我用wget在action下载sh脚本的时候遇到过。

**Comment by zhangguanzhang** [comment]
应该是这句 `gh auth login --with-token <<< ` 导致的，我看看管道可以不

**Comment by zhangguanzhang** [comment]
https://github.com/zhangguanzhang/Actions-OpenWrt/actions/runs/2438811367

**Comment by Misaka-Aki** [comment]
> https://github.com/zhangguanzhang/Actions-OpenWrt/actions/runs/2438811367

感谢，耐心等结果中

**Comment by zhangguanzhang** [comment]
> > https://github.com/zhangguanzhang/Actions-OpenWrt/actions/runs/2438811367
> 
> 感谢，耐心等结果中

编译好了。你fork后再试试吧，可能部分逻辑在fork有问题，不过有问题就反馈，我再修复

**Comment by Misaka-Aki** [comment]
> > > https://github.com/zhangguanzhang/Actions-OpenWrt/actions/runs/2438811367
> > 
> > 
> > 感谢，耐心等结果中
> 
> 编译好了。你fork后再试试吧，可能部分逻辑在fork有问题，不过有问题就反馈，我再修复

compile the firmware有点bug

To authenticate, please run `gh auth login`. 
51Error: Process completed with exit code 4.

**Comment by zhangguanzhang** [comment]
> > > > https://github.com/zhangguanzhang/Actions-OpenWrt/actions/runs/2438811367
> > > 
> > > 
> > > 感谢，耐心等结果中
> > 
> > 
> > 编译好了。你fork后再试试吧，可能部分逻辑在fork有问题，不过有问题就反馈，我再修复
> 
> compile the firmware有点bug
> 
> To authenticate, please run `gh auth login`. 51Error: Process completed with exit code 4.

331 行改成：
```
        if [ -n "${{ secrets.gh_token }}" ] && [ "${AutoBuildTimeOut}" == true ] ;then
```

**Comment by Misaka-Aki** [comment]
目前build没啥问题了，我仓库正在编译。我把你仓库里编译好的固件刷机了，发现默认没有开wifi。

**Comment by zhangguanzhang** [comment]
> 目前build没啥问题了，我仓库正在编译。我把你仓库里编译好的固件刷机了，发现默认没有开wifi。

默认是开的，wifi名字是Openwrt和Openwrt-5G

**Comment by Misaka-Aki** [comment]
> > 目前build没啥问题了，我仓库正在编译。我把你仓库里编译好的固件刷机了，发现默认没有开wifi。
> 
> 默认是开的，wifi名字是Openwrt和Openwrt-5G


额，我等了半天笔记本和手机都没搜索到，莫不是有什么bug，明天我再刷一次看看。

**Comment by zhangguanzhang** [comment]
> > > 目前build没啥问题了，我仓库正在编译。我把你仓库里编译好的固件刷机了，发现默认没有开wifi。
> > 
> > 
> > 默认是开的，wifi名字是Openwrt和Openwrt-5G
> 
> 额，我等了半天笔记本和手机都没搜索到，莫不是有什么bug，明天我再刷一次看看。

你笔记本连它的lan后看看能获取到dhcp不，能的话web上去看看，或者ssh上去
```
uci show wireless
```

**Comment by Misaka-Aki** [comment]
> 

 就是笔记本不太方便，一直以来openwrt接有线lan都进不了管理页面。改天用家里台式机试试。

**Comment by zhangguanzhang** [comment]
> > 
> 
> 就是笔记本不太方便，一直以来openwrt接有线lan都进不了管理页面。改天用家里台式机试试。

笔记本的网口配置成dhcp获取，然后cmd里看下ip获取到了没
```
ipconfig
```

**Comment by zhangguanzhang** [comment]
没事我就把issue关了

**Comment by Misaka-Aki** [comment]
> 没事我就把issue关了

行，先关吧。wifi我还没测，改天再试试。哦对了，安装的时候有提示未知版本号，版本过低，应该没啥问题。

**Comment by zhangguanzhang** [comment]
> > 没事我就把issue关了
> 
> 行，先关吧。wifi我还没测，改天再试试。哦对了，安装的时候有提示未知版本号，版本过低，应该没啥问题。

官方节目这个提示不用管，后续在op的界面上用sysupgrade那个tg文件升级就行了
