### ISSUE TITLE
哪个版本支持BCM5719这个网卡啊

### ISSUE THREAD

**Issue by onlypeng** [zhangguanzhang/Actions-OpenWrt#4]

**Comment by zhangguanzhang** [comment]
你不是x86_64的吗，可以 x86_64 的 slim版本，安装 `kmod-tg3` 就行

**Comment by onlypeng** [comment]
我把x86的lede和openwrt都下载下来试来着，lcsi查看存在网卡，但是就是识别不出来，我还以为下错版本了

**Comment by zhangguanzhang** [comment]
> 我把x86的lede和openwrt都下载下来试来着，lcsi查看存在网卡，但是就是识别不出来，我还以为下错版本了

我晚上下班回去调整下，等我后续消息吧，好了会给你说下，或者你现在不刷成其他的，后续我通知你在线升级扩容就行了

**Comment by onlypeng** [comment]
Ok 没问题



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月28日 18:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zhangguanzhang/Actions-OpenWrt] 哪个版本支持BCM5719这个网卡啊 (Issue #4) |

我把x86的lede和openwrt都下载下来试来着，lcsi查看存在网卡，但是就是识别不出来，我还以为下错版本了

我晚上下班回去调整下，等我后续消息吧，好了会给你说下，或者你现在不刷成其他的，后续我通知你在线升级扩容就行了

**Comment by zhangguanzhang** [comment]
> 

现在 lede 的x86_64编译好了，如果你用openwrt 21.02的就等这个完成 https://github.com/zhangguanzhang/Actions-OpenWrt/actions/runs/2753416549

**Comment by onlypeng** [comment]
OK 谢谢！！

**Comment by zhangguanzhang** [comment]
咋样了

**Comment by onlypeng** [comment]
> 咋样了
进去有kmod-tg3，安装上，网卡可以使用了，

**Comment by zhangguanzhang** [comment]
slim目前的保留列表针目前没保留kmod，如果你升级的话可能需要再安装下 kmod-tg3 了
