### ISSUE TITLE
大佬求个你的仓库的编译教程

### ISSUE THREAD

**Issue by zaishi0103** [zhangguanzhang/Actions-OpenWrt#9]
大佬求个你的仓库的编译教程

**Comment by zaishi0103** [comment]
gh token有了，dockerhub也有了，直接填进，build.yml吗

**Comment by zhangguanzhang** [comment]
> gh token有了，dockerhub也有了，直接填进，build.yml吗

你仓库的Settings里去设置secret env，key是我脚本里的key，value是你自己的

**Comment by zaishi0103** [comment]
没搞过github还是不太懂，大佬多多指教吧
![Screenshot_2022-10-30-22-09-20-038_com android chrome](https://user-images.githubusercontent.com/34189712/198883156-91389e39-bb78-437d-9016-8ef18888ebd8.jpg)

**Comment by zaishi0103** [comment]
不太懂

**Comment by zaishi0103** [comment]
![Screenshot_2022-10-30-22-12-59-758_com android chrome](https://user-images.githubusercontent.com/34189712/198883290-601228ad-5574-484b-9de9-c9f5651f3079.jpg)

**Comment by zhangguanzhang** [comment]
![image](https://user-images.githubusercontent.com/18641678/198885676-de9f7632-21ef-4ffa-9066-065a892ed9f1.png)

**Comment by zaishi0103** [comment]
gh_package_token是哪个，从哪里取到。aliyun注释掉了是吧，可以不用？

**Comment by zaishi0103** [comment]
大佬编译出来的不和你的一样呢也没有full smil
@zhangguanzhang 
![Uploading Screenshot_2022-10-31-05-05-22-118_com.android.chrome.jpg…]()

**Comment by zaishi0103** [comment]
![Screenshot_2022-10-31-05-05-22-118_com android chrome](https://user-images.githubusercontent.com/34189712/198901750-0e783417-c7f1-4c4b-b721-c045a36c4813.jpg)

**Comment by zaishi0103** [comment]
LEDE直接编译失败

**Comment by zaishi0103** [comment]
![Screenshot_2022-10-31-05-58-15-154_com android chrome](https://user-images.githubusercontent.com/34189712/198903520-6d22caf3-c4d5-4100-900c-580e88d59360.jpg)
哪里的问题呢

**Comment by zaishi0103** [comment]
![Screenshot_2022-10-31-05-58-15-154_com android chrome](https://user-images.githubusercontent.com/34189712/198903545-6d95dafb-db13-45cd-be80-8cf99e32e97c.jpg)

**Comment by zaishi0103** [comment]
大佬在吗

**Comment by zhangguanzhang** [comment]
```
From https://github.com/zaishi0103/Actions-OpenWrt
 * [new branch]      zaishi0103-patch-1 -> origin/zaishi0103-patch-1
 * [new tag]         2022.10.30-0353    -> 2022.10.30-0353
 * [new tag]         2022.10.30-0407    -> 2022.10.30-0407
HEAD is now at e4e7de6 Update build.yml
```

你需要你的main是head，或者你把我昨天的合并pick到你的head分支上

**Comment by zaishi0103** [comment]
大佬，合并了好像可以了

**Comment by zaishi0103** [comment]
还是有点错误
![Screenshot_2022-10-31-15-56-51-830_com android chrome](https://user-images.githubusercontent.com/34189712/198959289-218b103d-afb5-4382-8323-15d1d58d71a3.jpg)

**Comment by zhangguanzhang** [comment]
imageBuilder 没构建出来，你可以再点一个试试，compiler阶段超时了 https://github.com/zaishi0103/Actions-OpenWrt/actions/runs/3357987478/jobs/5564342123#step:17:825

**Comment by zhangguanzhang** [comment]
imageBuilder 没构建出来，你可以再点一个试试，compiler阶段超时了 https://github.com/zaishi0103/Actions-OpenWrt/actions/runs/3357987478/jobs/5564342123#step:17:825

**Comment by zaishi0103** [comment]
大佬添加ipk的话往哪个文件里写，我改了build.config没起作用呢

**Comment by zaishi0103** [comment]
config.buildinfo

**Comment by zaishi0103** [comment]
![Uploading Screenshot_2022-10-31-19-43-57-936_com.android.chrome.jpg…]()

**Comment by zaishi0103** [comment]
![Screenshot_2022-10-31-19-43-57-936_com android chrome](https://user-images.githubusercontent.com/34189712/199000548-6f59aa96-3719-44e4-99f3-35764c835452.jpg)
问题还是存在

**Comment by zhangguanzhang** [comment]
我是说让你重新run一个x86的，action的机器cpu频率不是固定的，有时候很小只有2000，最好的是2700多

**Comment by zaishi0103** [comment]
我怎么添加luci-app-ipsec-vpnd呢

**Comment by zaishi0103** [comment]
![Screenshot_2022-11-01-09-35-21-877_com android chrome](https://user-images.githubusercontent.com/34189712/199139920-1530db92-5e24-4ab0-8170-8f2aebd5a248.jpg)
这是咋了

**Comment by zaishi0103** [comment]
ipsec你的本地包里真没有

**Comment by zhangguanzhang** [comment]
```
root@OpenWrt:~# ls -l /local_feed/luci-app-ip*
-rw-r--r--    1 root     root          7868 Oct  8 11:16 /local_feed/luci-app-ipsec-server_20211223-2_all.ipk
-rw-r--r--    1 root     root          6187 Oct  8 11:16 /local_feed/luci-app-ipsec-vpnd_1.0-11_all.ipk
```

**Comment by zaishi0103** [comment]
我下载的你的包，和我自己打包的那个都没有

**Comment by zhangguanzhang** [comment]
ssh上去的banner信息和我ls的命令输出复制上来

**Comment by zaishi0103** [comment]
![Screenshot_2022-11-01-09-55-34-018_com sonelli juicessh](https://user-images.githubusercontent.com/34189712/199141806-6176b6ef-9119-4f4e-ac3a-ede9fa11f57a.jpg)

**Comment by zaishi0103** [comment]
这是用的你github的slim, [

**Comment by zhangguanzhang** [comment]
根目录，你路径都打错了

**Comment by zhangguanzhang** [comment]
你要不然去我博客加下我微信吧，你这交流太慢了

**Comment by zaishi0103** [comment]
对啊

**Comment by zaishi0103** [comment]
博客地址发下呗
